<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260712075011 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE inbound_email (id UUID NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, from_address VARCHAR(320) NOT NULL, to_address VARCHAR(320) NOT NULL, subject VARCHAR(998) NOT NULL, raw_message TEXT NOT NULL, kind VARCHAR(32) NOT NULL, surrogate_user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B3E134884564D90C ON inbound_email (surrogate_user_id)');
        $this->addSql('CREATE TABLE message_map (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, discourse_post_id INT NOT NULL, discourse_topic_id INT NOT NULL, email_message_id VARCHAR(255) NOT NULL, source VARCHAR(32) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA982057A8E8CDF7 ON message_map (discourse_post_id)');
        $this->addSql('CREATE INDEX IDX_BA982057FFC9E1F6 ON message_map (email_message_id)');
        $this->addSql('CREATE TABLE outbound_message (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT DEFAULT NULL, discourse_user_id INT NOT NULL, discourse_post_id INT NOT NULL, discourse_topic_id INT NOT NULL, message_id VARCHAR(255) NOT NULL, subject VARCHAR(998) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4F62714CA8E8CDF7 ON outbound_message (discourse_post_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4F62714C537A1329 ON outbound_message (message_id)');
        $this->addSql('CREATE TABLE surrogate_user (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, discourse_user_id INT NOT NULL, discourse_username VARCHAR(255) NOT NULL, display_name VARCHAR(255) NOT NULL, real_email VARCHAR(320) NOT NULL, surrogate_address VARCHAR(320) NOT NULL, status VARCHAR(32) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DC74FCBC440F1D4E ON surrogate_user (discourse_user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DC74FCBC8BFD4EC7 ON surrogate_user (real_email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DC74FCBCEF446518 ON surrogate_user (surrogate_address)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE inbound_email ADD CONSTRAINT FK_B3E134884564D90C FOREIGN KEY (surrogate_user_id) REFERENCES surrogate_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inbound_email DROP CONSTRAINT FK_B3E134884564D90C');
        $this->addSql('DROP TABLE inbound_email');
        $this->addSql('DROP TABLE message_map');
        $this->addSql('DROP TABLE outbound_message');
        $this->addSql('DROP TABLE surrogate_user');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
